### ISSUE TITLE
improve readme with best practice about envs

### ISSUE THREAD

**Issue by ranska** [mailin-api/sendinblue-ruby-gem#1]
Hello,
Sendinblue look very intersting.
But there is some spécifics dark points that I want to enlight before using it in production.

Smtp service use différent configuration depend on what environment you are.
E.I. prod, staging but also dev and test (particularly intégration test where sending mail are involved).

What is the correct way to use it during test for exemple ?
can we mock or best unactivate it,

**Comment by pierrre** [comment]
It depends:

If you want to send a different email on prod and dev environments,
you can create 2 differents email templates, and select the one you want to use depending on the current environnment.

If you want to disable email, you should do it on your side.
