### ISSUE TITLE
Sending to multiple recipients in transaction email API

### ISSUE THREAD

**Issue by MartinM25** [mailin-api/sendinblue-ruby-gem#10]
how do you send one email to multiple recipients in transactional email using the API
i am connecting my angular project to the API
tried to use the examples used in the docs: https://apidocs.sendinblue.com/tutorial-sending-transactional-email/
but i keep getting an error

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-ruby-library
