### ISSUE TITLE
invalid example code?

### ISSUE THREAD

**Issue by daniely** [mailin-api/sendinblue-ruby-gem#3]
The docs show the following to set "to" field for an email:
    `data = { "to" => {"to@example.net"=>"to whom!"} }`

But it doesn't seem to work. I had to use:
    `data = { "to" => "to@example.net" }`

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.
Issue discussed & closed here https://github.com/mailin-api/sendinblue-ruby-gem/issues/4

Regards
SendinBlue Team
