### ISSUE TITLE
example for sending to multiple recipents

### ISSUE THREAD

**Issue by daniely** [mailin-api/sendinblue-ruby-gem#4]
It would be helpful to show how to send to multiple recipients. You do so by | delimiting a string. e.g.

`"to" => "email_one@test.com|email_two@test.com"`

The above will send emails to `email_one` and `email_two`

**Comment by fluxsaas** [comment]
does that actually work for you?

the API says:

> Email address of the recipient(s). It should be sent as an associative array. Example: array(“to@example.net”=>”to whom”). You can use commas to separate multiple recipients [Mandatory].

https://apidocs.sendinblue.com/tutorial-sending-transactional-email/


for me, this works:

`data = {
  "to" => {"email_one@example.de" => "Admin", "email_two@example.de" => "Admin"},
  ...
}`

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

We have two different APIs, transactional mails & transactional template mails.

@daniely We use this format `"to" => "email_one@test.com|email_two@test.com" ` in transactional template API ( https://apidocs.sendinblue.com/template/#1 )

@fluxsaas Your reply to this query is absolutely correct, we use this format `data = { "to" => {"email_one@example.de" => "Admin", "email_two@example.de" => "Admin"}, ... }` in transactional mail API ( https://apidocs.sendinblue.com/tutorial-sending-transactional-email/ )

Hope that helps!

Regards
SendinBlue Team
