### ISSUE TITLE
Subscribe user WITH double-optin

### ISSUE THREAD

**Issue by Tails** [mailin-api/sendinblue-ruby-gem#5]
Currently, it's possible to add a subscriber to a list, but it's not possible to have this trigger a double op-in confirmation.

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

The double opt-in feature is managed only in [subscription forms](https://help.sendinblue.com/hc/en-us/articles/208771869-Create-a-subscription-form) & not in the APIs.

Regards
SendinBlue Team

**Comment by Tails** [comment]
But why?

**Comment by ekta-slit** [comment]
Based on our customers query we are planning to implement this feature soon in our new API version 3.0

**Comment by LudovicFauchet** [comment]
@ekta-slit Hello, some news about this feature ?

**Comment by Tails** [comment]
I am curious as well, though we went serverless partly because of issues like this.
