### ISSUE TITLE
How to use it with Ruby on Rails?

### ISSUE THREAD

**Issue by Paxa** [mailin-api/sendinblue-ruby-gem#6]
Does it provide any integration with ActionMailer?

**Comment by arni1981** [comment]
This worked for me, put it in config/environments/production.rb

  config.action_mailer.default_url_options = { :host => "example.com" }

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
      :address              => 'smtp-relay.sendinblue.com',
      :port                 => 587,
      :domain               => 'example.com',
      :user_name            => 'your@email.com',
      :password             => 'YOUR PASSWORD',
      :authentication       => 'login',
      :enable_starttls_auto => true
  }

**Comment by nywton** [comment]
Can i use without a domain?

**Comment by miagenovese** [comment]
but isn't there a more secure way to add your username and password? For example with SendGrid you'd write ENV['SENDGRID_USERNAME'] and ENV['SENDGRID_PASSWORD']... Asking because I'm trying to switch from SendGrid to SendInBlue =)

**Comment by Tails** [comment]
Just watch out if you want to add subscribers like this, since double opt-in is not supported. See #5.

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-ruby-library
