### ISSUE TITLE
Can I use the gem with Sidekiq?

### ISSUE THREAD

**Issue by brunomperes** [mailin-api/sendinblue-ruby-gem#7]
First, thanks a bunch for this!
I'm moving from another mailing alternative and I'm really liking sendinblue!

Is it possible to integrate the gem with Sidekiq?

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-ruby-library
