### ISSUE TITLE
<NoMethodError: undefined method `display_list_users' for #<Sendinblue::Mailin>

### ISSUE THREAD

**Issue by jorge627** [mailin-api/sendinblue-ruby-gem#8]
This method is present in Sendinblue APIDOC (https://apidocs.sendinblue.com/list/#8) but it is not implemented in the gem ?

Thanks

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-ruby-library
